function displayResults( ...
    m_ox_kg, m_fuel_kg, m_pressurant_gas_kg,                                ...
    m_empty_ox_tank_kg, m_empty_fuel_tank_kg, m_empty_pressurant_tank_kg,   ...
    m_misc_and_plumbing_kg, m_final_kg, m_total_kg,                         ...
    d_ox_tank_m, t_cyl_ox_m, l_ox_tank_total_m,                            ...
    d_fuel_tank_m, t_cyl_fuel_m, l_fuel_tank_total_m,                      ...
    d_pressurant_tank_outer_m, r_pressurant_internal_m, r_pressurant_outer_m, ...
    t_pressurant_tank_m, l_pressurant_tank_total_m,                         ...
    l_total_vehicle_m, twr_ratio, delta_v_ms, f_drag_max_n, maxq_pa, h_max_m, ...
    l_cyl_ox_m, l_cyl_fuel_m,                                                          ...
    v_ox_m3, v_fuel_m3, v_total_ox_tank_m3, v_total_fuel_tank_m3, v_pressurant_tank_m3, ...
    m_pressurant_gas_isothermal_kg, v_storage_isothermal_L,                             ...
    m_pressurant_gas_thermal_kg, v_storage_thermal_L,                                   ...
    m_pressurant_gas_v1_thermal_kg, v_storage_v1_thermal_L,                             ...
    T_ox_history_K, T_fuel_history_K, t_history_s,                                      ...
    T_pt_history_K, T_wall_history_K,                                                   ...
    p_pt_history_pa, m_pt_history_kg,                                                   ...
    m_ox_ullage_history_kg, m_fuel_ullage_history_kg,                                   ...
    P, C)
%{
---------------------------------------------------------------------------
displayResults
  Runs all design validation checks, then prints all calculated values to
  the command window in a formatted table. Any warnings generated by the
  validation checks are printed at the bottom of the output block.
  Also generates plots of the pressurant system thermal state over time,
  including a mass conservation verification plot.

  Part of:  VAPOR - Volumetric Analysis & Pressurant Output Report

Inputs: (all computed values from the calculation functions)
  See variable names - each maps directly to a computed result.
  P  - [struct] Design inputs from getInputs()   (uses constraint limits)
  C  - [struct] Physical constants from getConstants()  (uses unit conversions)

Outputs:
  None (prints to command window and generates figures)
---------------------------------------------------------------------------
%}

%% --- VALIDATION CHECKS ---
warning_messages = {};

if twr_ratio < P.twr_minimum_ratio
    warning_messages{end+1} = sprintf('TWR is %.2f, which is below the minimum requirement of %.1f.', twr_ratio, P.twr_minimum_ratio);
end
if l_total_vehicle_m > P.l_airframe_max_m
    warning_messages{end+1} = sprintf('Estimated vehicle length (%.2f m) exceeds max airframe length (%.2f m).', l_total_vehicle_m, P.l_airframe_max_m);
end
if l_cyl_ox_m < 0
    warning_messages{end+1} = 'Invalid LOX tank geometry: Cylindrical section length is negative. End caps are too large for the required volume.';
end
if l_cyl_fuel_m < 0
    warning_messages{end+1} = 'Invalid Fuel tank geometry: Cylindrical section length is negative. End caps are too large for the required volume.';
end
if P.ullage_fraction_fuel <= 0 || P.ullage_fraction_fuel >= 1 || P.ullage_fraction_ox <= 0 || P.ullage_fraction_ox >= 1
    warning_messages{end+1} = 'Ullage fraction must be between 0 and 1.';
end
if P.safety_factor <= 1
    warning_messages{end+1} = 'Safety factor should be greater than 1.';
end

%% --- OUTPUT DISPLAY ---

d_ox_tank_inner_m           = d_ox_tank_m - 2 * t_cyl_ox_m;
d_fuel_tank_inner_m         = d_fuel_tank_m - 2 * t_cyl_fuel_m;
d_pressurant_tank_inner_m   = 2 * r_pressurant_internal_m;
t_pressurant_total_m        = r_pressurant_outer_m - r_pressurant_internal_m;

fprintf('\n');
fprintf('=====================================================================\n');
fprintf('  VAPOR - Volumetric Analysis & Pressurant Output Report\n');
fprintf('  Run Header & Design Assumptions\n');
fprintf('=====================================================================\n');
fprintf('  Vehicle Config:        %s\n', P.vehicle_name);
if isfield(P, 'stack_order')
    fprintf('  Tank Stack Order:      %s\n', P.stack_order);
else
    fprintf('  Tank Stack Order:      LOX_BOTTOM_BASELINE (default)\n');
end
fprintf('  Tank Outer Diameter:   %.4f m (%.3f in)\n', P.d_tank_outer_m, P.d_tank_outer_m * C.M_TO_IN);
if strcmp(P.vehicle_name, 'Scorpion')
    fprintf('                         (Note: 6.675 in actual OD for 6 in nominal tank size)\n');
end
if P.use_cots_tank
    if isfield(P, 'pressurant_tank_name')
        fprintf('  COTS Pressurant Tank:  %s\n', P.pressurant_tank_name);
    else
        fprintf('  COTS Pressurant Tank:  ME36 (default)\n');
    end
else
    fprintf('  COTS Pressurant Tank:  None (Custom COPV calculated)\n');
end
fprintf('  LOX Ullage Fraction:   %.2f%%\n', P.ullage_fraction_ox * 100);
fprintf('  Fuel Ullage Fraction:  %.2f%%\n', P.ullage_fraction_fuel * 100);
fprintf('=====================================================================\n\n');

fprintf('=====================================================================\n');
fprintf('  %s Vehicle Mass & Tank Design Results\n', P.vehicle_name);
fprintf('=====================================================================\n\n');

% --- Mass Breakdown ---
fprintf('--- Mass Breakdown ---\n');
fprintf('  Oxidizer Mass (LOX):          %8.2f kg\n', m_ox_kg);
fprintf('  Fuel Mass (Jet-A):            %8.2f kg\n', m_fuel_kg);
fprintf('  Pressurant Gas Mass (N2):     %8.2f kg\n', m_pressurant_gas_kg);
fprintf('  ------------------------------------------\n');
fprintf('  Total Propellant Mass:        %8.2f kg\n', m_ox_kg + m_fuel_kg + m_pressurant_gas_kg);
fprintf('  ------------------------------------------\n');
fprintf('  Empty LOX Tank Mass:          %8.2f kg\n', m_empty_ox_tank_kg);
fprintf('  Empty Fuel Tank Mass:         %8.2f kg\n', m_empty_fuel_tank_kg);
fprintf('  Empty Pressurant Tank Mass:   %8.2f kg\n', m_empty_pressurant_tank_kg);
fprintf('  Plumbing & Misc Mass:         %8.2f kg\n', m_misc_and_plumbing_kg);
fprintf('  ------------------------------------------\n');
fprintf('  Dry Mass (Final):             %8.2f kg\n', m_final_kg);
fprintf('  Wet Mass (Liftoff):           %8.2f kg\n\n', m_total_kg);

% --- Volume Breakdown ---
fprintf('--- Volume Breakdown ---\n');
fprintf('  LOX Volume (propellant only):    %8.4f m^3  (%8.2f L)\n', v_ox_m3,             v_ox_m3*1000);
fprintf('  LOX Tank Volume (with ullage):   %8.4f m^3  (%8.2f L)\n', v_total_ox_tank_m3,  v_total_ox_tank_m3*1000);
fprintf('  Fuel Volume (propellant only):   %8.4f m^3  (%8.2f L)\n', v_fuel_m3,            v_fuel_m3*1000);
fprintf('  Fuel Tank Volume (with ullage):  %8.4f m^3  (%8.2f L)\n', v_total_fuel_tank_m3, v_total_fuel_tank_m3*1000);
fprintf('  Pressurant Tank Volume:          %8.4f m^3  (%8.2f L)\n\n', v_pressurant_tank_m3, v_pressurant_tank_m3*1000);

% --- Tank Geometry ---
fprintf('--- LOX Tank ---\n');
fprintf('  Outer Diameter:  %8.4f m  (%8.2f in)  (%8.2f ft)\n', d_ox_tank_m, d_ox_tank_m*C.M_TO_IN, d_ox_tank_m*C.M_TO_FT);
fprintf('  Inner Diameter:  %8.4f m  (%8.2f in)  (%8.2f ft)\n', d_ox_tank_inner_m, d_ox_tank_inner_m*C.M_TO_IN, d_ox_tank_inner_m*C.M_TO_FT);
fprintf('  Wall Thickness:  %8.4f m  (%8.2f mm)  (%8.3f in)\n', t_cyl_ox_m, t_cyl_ox_m*C.M_TO_MM, t_cyl_ox_m*C.M_TO_IN);
fprintf('  Total Length:    %8.4f m  (%8.2f in)  (%8.2f ft)\n', l_ox_tank_total_m, l_ox_tank_total_m*C.M_TO_IN, l_ox_tank_total_m*C.M_TO_FT);
fprintf('  Total Mass:      %8.2f kg\n\n', m_empty_ox_tank_kg + m_ox_kg);

fprintf('--- Fuel Tank ---\n');
fprintf('  Outer Diameter:  %8.4f m  (%8.2f in)  (%8.2f ft)\n', d_fuel_tank_m, d_fuel_tank_m*C.M_TO_IN, d_fuel_tank_m*C.M_TO_FT);
fprintf('  Inner Diameter:  %8.4f m  (%8.2f in)  (%8.2f ft)\n', d_fuel_tank_inner_m, d_fuel_tank_inner_m*C.M_TO_IN, d_fuel_tank_inner_m*C.M_TO_FT);
fprintf('  Wall Thickness:  %8.4f m  (%8.2f mm)  (%8.3f in)\n', t_cyl_fuel_m, t_cyl_fuel_m*C.M_TO_MM, t_cyl_fuel_m*C.M_TO_IN);
fprintf('  Total Length:    %8.4f m  (%8.2f in)  (%8.2f ft)\n', l_fuel_tank_total_m, l_fuel_tank_total_m*C.M_TO_IN, l_fuel_tank_total_m*C.M_TO_FT);
fprintf('  Total Mass:      %8.2f kg\n\n', m_empty_fuel_tank_kg + m_fuel_kg);

fprintf('--- Pressurant Tank (COPV / COTS) ---\n');
fprintf('  Outer Diameter:  %8.4f m  (%8.2f in)  (%8.2f ft)\n', d_pressurant_tank_outer_m, d_pressurant_tank_outer_m*C.M_TO_IN, d_pressurant_tank_outer_m*C.M_TO_FT);
fprintf('  Inner Diameter:  %8.4f m  (%8.2f in)  (%8.2f ft)\n', d_pressurant_tank_inner_m, d_pressurant_tank_inner_m*C.M_TO_IN, d_pressurant_tank_inner_m*C.M_TO_FT);
fprintf('  Wall Thickness:  %8.4f m  (%8.2f mm)  (%8.3f in)\n', t_pressurant_total_m, t_pressurant_total_m*C.M_TO_MM, t_pressurant_total_m*C.M_TO_IN);
fprintf('  Total Length:    %8.4f m  (%8.2f in)  (%8.2f ft)\n', l_pressurant_tank_total_m, l_pressurant_tank_total_m*C.M_TO_IN, l_pressurant_tank_total_m*C.M_TO_FT);
fprintf('  Total Mass:      %8.2f kg\n\n', m_empty_pressurant_tank_kg + m_pressurant_gas_kg);

fprintf('--- Total Component Stackup ---\n');
fprintf('  Total Length:    %8.4f m  (%8.2f in)  (%8.2f ft)\n\n', l_total_vehicle_m, l_total_vehicle_m*C.M_TO_IN, l_total_vehicle_m*C.M_TO_FT);

% --- Performance ---
fprintf('--- Performance ---\n');
fprintf('  Liftoff TWR:        %8.2f\n', twr_ratio);
fprintf('  Ideal Delta-V:      %8.2f m/s\n', delta_v_ms);
fprintf('  Max Drag Force:     %8.2f N\n', f_drag_max_n);
fprintf('  Max Q:              %8.2f Pa\n', maxq_pa);
fprintf('  Estimated Apogee:   %8.2f m    (%8.2f ft)\n\n', h_max_m, h_max_m/0.3048);

% ======================================================================
%  PRESSURANT ANALYSIS RESULTS
%  The active model result is shown first and prominently.
%  Previous models are shown below for comparison only.
% ======================================================================
fprintf('=====================================================================\n');
fprintf('  PRESSURANT ANALYSIS RESULTS\n');
fprintf('=====================================================================\n\n');

% --- Active Result (the number that matters) ---
if P.use_thermal_model && P.use_blowdown_model
    active_label = 'V2 Coupled Blowdown Model';
elseif P.use_thermal_model
    active_label = 'V1 Thermal Model (constant inlet)';
else
    active_label = 'Isothermal Model (conservative)';
end

% --- Find exact time pressure hits 1000 PSI ---
% This is the time at which the PT can no longer maintain operating
% pressure (1000 PSI) in the propellant tanks.
time_to_1000_s = NaN;
if ~isempty(p_pt_history_pa)
    p_op_max_pa = max(P.p_op_ox_tank_pa, P.p_op_fuel_tank_pa);   % [Pa] Max operating pressure
    idx_1000 = find(p_pt_history_pa < p_op_max_pa, 1);            % First index below operating pressure
    if ~isempty(idx_1000)
        time_to_1000_s = t_history_s(idx_1000);
    end
end

if P.use_cots_tank
    cots_vol_L = P.cots_tank_volume_m3 * 1000;
    tank_name = 'ME36';
    if isfield(P, 'pressurant_tank_name')
        tank_name = P.pressurant_tank_name;
    end
    fprintf('  >>> ACTIVE MODEL (COTS): %s <<<\n', active_label);
    fprintf('  Selected COTS Tank:              %s\n', tank_name);
    fprintf('  Selected COTS Tank Volume:       %8.2f L   (%.4f m^3)\n', cots_vol_L, P.cots_tank_volume_m3);
    fprintf('  Loaded N2 Mass in Selected Tank: %8.4f kg\n', m_pressurant_gas_thermal_kg);
else
    fprintf('  >>> ACTIVE MODEL (COPV): %s <<<\n', active_label);
    fprintf('  Total N2 Mass Required (Loaded): %8.4f kg\n', m_pressurant_gas_thermal_kg);
    fprintf('  Exact Required Tank Volume:      %8.2f L   (%.4f m^3)\n', v_storage_thermal_L, v_storage_thermal_L/1000);
end

% Print the time to minimum pressure if the pressure data exists
if ~isnan(time_to_1000_s)
    fprintf('  Time to operating pressure limit: %8.2f s   (PT drops below %.0f PSI)\n', ...
        time_to_1000_s, p_op_max_pa * C.PA_TO_PSI);
else
    if ~isempty(p_pt_history_pa)
        fprintf('  PT stays above operating pressure for entire burn.\n');
    end
end
fprintf('\n');

% --- Comparison Table ---
fprintf('  --- Model Comparison (for reference) ---\n');
fprintf('  %-42s %8.4f kg   %8.2f L\n', 'Isothermal (conservative baseline):', m_pressurant_gas_isothermal_kg, v_storage_isothermal_L);

if P.use_thermal_model
    reduction_v1 = (1 - m_pressurant_gas_v1_thermal_kg / m_pressurant_gas_isothermal_kg) * 100;
    fprintf('  %-42s %8.4f kg   %8.2f L   (%.1f%% vs isothermal)\n', 'V1 Thermal (constant inlet, old):', m_pressurant_gas_v1_thermal_kg, v_storage_v1_thermal_L, -reduction_v1);
end

if P.use_thermal_model && P.use_blowdown_model
    reduction_v2    = (1 - m_pressurant_gas_thermal_kg / m_pressurant_gas_isothermal_kg) * 100;
    increase_vs_v1  = (m_pressurant_gas_thermal_kg / m_pressurant_gas_v1_thermal_kg - 1) * 100;
    fprintf('  %-42s %8.4f kg   %8.2f L   (%.1f%% vs isothermal, +%.1f%% vs V1)\n', ...
        'V2 Blowdown (active):', m_pressurant_gas_thermal_kg, v_storage_thermal_L, -reduction_v2, increase_vs_v1);
end
fprintf('\n');

% --- Warnings ---
if ~isempty(warning_messages)
    fprintf('!!! --- WARNINGS --- !!!\n');
    for i = 1:length(warning_messages)
        fprintf('  - %s\n', warning_messages{i});
    end
    fprintf('!!! ------------------ !!!\n');
else
    fprintf('--- All design checks passed. ---\n');
end

%% ====================================================================
%  PLOTS - Pressurant System Thermal Analysis
%  ====================================================================

if isempty(t_history_s)
    return; % No thermal data to plot
end

lw = 1.5;  % Default line width for all plots

% =====================================================================
%  FIGURE 1: Main Thermal Analysis (2x2 subplots)
% =====================================================================

% --- 1. Identify Key Configuration Data for Header ---
if P.use_cots_tank
    tank_name = 'ME36';
    if isfield(P, 'pressurant_tank_name')
        tank_name = P.pressurant_tank_name;
    end
    tank_type = ['COTS (' tank_name ')'];
else
    tank_type = 'Custom COPV';
end

% --- 2. Calculate Milestone Indices (1000 PSI Limit) ---
p_op_limit_pa = max(P.p_op_ox_tank_pa, P.p_op_fuel_tank_pa);
idx_limit = find(p_pt_history_pa < p_op_limit_pa, 1);
if isempty(idx_limit); idx_limit = length(t_history_s); end

fig = figure('Name','VAPOR (Volumetric Analysis & Pressurant Output Report) - Pressurant System Thermal Analysis','NumberTitle','off', ...
       'Position',[100 100 1600 1000]);
try
    fig.Theme = 'light';
catch
    set(fig, 'Color', 'w');
end

% --- Subplot 1: Pressurant Tank Pressure During Blowdown ---
if ~isempty(p_pt_history_pa)
    subplot(2,3,1);

    % Convert to display units
    p_kPa = p_pt_history_pa / 1000;      % [kPa]
    p_PSI = p_pt_history_pa * C.PA_TO_PSI; % [PSI]

    % Plot on left axis (kPa)
    yyaxis left
    plot(t_history_s, p_kPa, 'b-', 'LineWidth', lw);
    ylabel('Pressure [kPa]');

    % Set left axis limits explicitly starting from zero
    kPa_max = ceil(max(p_kPa) / 1000) * 1000;
    kPa_min = 0;
    ylim([kPa_min, kPa_max]);
    left_lims = ylim;

    % Right axis (PSI) — linked to left axis limits by unit conversion
    yyaxis right
    ylim(left_lims * 1000 * C.PA_TO_PSI);
    ylabel('Pressure [PSI]');

    % Add the operating pressure limit line on the right axis
    p_op_max_psi = max(P.p_op_ox_tank_pa, P.p_op_fuel_tank_pa) * C.PA_TO_PSI;
    yline(p_op_max_psi, 'r--', sprintf('%.0f PSI (Op. Limit)', p_op_max_psi), ...
        'LineWidth', lw, 'LabelHorizontalAlignment', 'left');

    xlabel('Time [s]');
    title('Pressurant Tank Pressure During Blowdown');
    grid on;

    ax = gca;
    ax.YAxis(1).Color = 'k';
    ax.YAxis(2).Color = 'k';

    % --- Annotation: Key pressure milestones ---
    p_start_psi = p_pt_history_pa(1) * C.PA_TO_PSI;
    p_at_limit_psi = p_pt_history_pa(idx_limit) * C.PA_TO_PSI;
    p_end_psi = p_pt_history_pa(end) * C.PA_TO_PSI;
    annotation_str = sprintf('Start: %.0f PSI | At Op. Limit (t=%.2fs): %.0f PSI | End: %.0f PSI', ...
        p_start_psi, t_history_s(idx_limit), p_at_limit_psi, p_end_psi);
    text(0.5, -0.18, annotation_str, 'Units', 'normalized', ...
        'HorizontalAlignment', 'center', 'FontSize', 8);
end

% --- Subplot 2: Propellant Ullage Gas Temperatures ---
subplot(2,3,2);
yyaxis left
plot(t_history_s, T_ox_history_K,   '-', 'LineWidth', lw, 'Color', [0.00 0.45 0.74]); hold on;
plot(t_history_s, T_fuel_history_K, '-', 'LineWidth', lw, 'Color', [0.85 0.33 0.10]);
ylabel('Temperature [K]');
left_lims = ylim;

yyaxis right
ylim(left_lims - 273.15);
ylabel('Temperature [\circC]');

xlabel('Time [s]');
title('Propellant Tanks Ullage Gas Temp');
legend('LOX Tank Ullage', 'Fuel Tank Ullage', 'Location', 'best');
grid on;
ax = gca; ax.YAxis(1).Color = 'k'; ax.YAxis(2).Color = 'k';

% --- Annotation: Key temperature milestones ---
T_ox_start_K  = T_ox_history_K(1);
T_fuel_start_K = T_fuel_history_K(1);
T_ox_limit_K  = T_ox_history_K(idx_limit);
T_fuel_limit_K = T_fuel_history_K(idx_limit);
T_ox_end_K    = T_ox_history_K(end);
T_fuel_end_K  = T_fuel_history_K(end);
annotation_str = sprintf('LOX: %.1fK \\rightarrow %.1fK (At Op. Limit) \\rightarrow %.1fK | Fuel: %.1fK \\rightarrow %.1fK \\rightarrow %.1fK', ...
    T_ox_start_K, T_ox_limit_K, T_ox_end_K, T_fuel_start_K, T_fuel_limit_K, T_fuel_end_K);
text(0.5, -0.18, annotation_str, 'Units', 'normalized', ...
    'HorizontalAlignment', 'center', 'FontSize', 8);

% --- Subplot 3: Pressurant Tank Gas & Wall Temperatures ---
if ~isempty(T_pt_history_K)
    subplot(2,3,3);
    yyaxis left
    plot(t_history_s, T_pt_history_K,   '-',  'LineWidth', lw, 'Color', [0.85 0.33 0.10]); hold on;
    plot(t_history_s, T_wall_history_K, '--', 'LineWidth', lw, 'Color', [0.47 0.67 0.19]);
    ylabel('Temperature [K]');
    left_lims = ylim;

    yyaxis right
    ylim(left_lims - 273.15);
    ylabel('Temperature [\circC]');

    xlabel('Time [s]');
    title('Pressurant Tank Gas & Wall Temp');
    legend('N_2 Gas', 'Al Wall', 'Location', 'best');
    grid on;
    ax = gca; ax.YAxis(1).Color = 'k'; ax.YAxis(2).Color = 'k';

    % --- Annotation: Key temperature milestones ---
    T_gas_start_K  = T_pt_history_K(1);
    T_wall_start_K = T_wall_history_K(1);
    T_gas_limit_K  = T_pt_history_K(idx_limit);
    T_wall_limit_K = T_wall_history_K(idx_limit);
    T_gas_end_K    = T_pt_history_K(end);
    T_wall_end_K   = T_wall_history_K(end);
    annotation_str = sprintf('N_2: %.1fK \\rightarrow %.1fK (At Op. Limit) \\rightarrow %.1fK | Wall: %.1fK \\rightarrow %.1fK \\rightarrow %.1fK', ...
        T_gas_start_K, T_gas_limit_K, T_gas_end_K, T_wall_start_K, T_wall_limit_K, T_wall_end_K);
    text(0.5, -0.18, annotation_str, 'Units', 'normalized', ...
        'HorizontalAlignment', 'center', 'FontSize', 8);
end

% --- Subplot 4: N2 Mass Distribution ---
if ~isempty(m_pt_history_kg)
    subplot(2,3,4);

    % Compute total N2 mass at each timestep for verification
    m_total_n2_history = m_pt_history_kg + m_ox_ullage_history_kg + m_fuel_ullage_history_kg; % [kg]

    plot(t_history_s, m_pt_history_kg,         '-',  'LineWidth', lw, 'Color', [0.49 0.18 0.56]); hold on;
    plot(t_history_s, m_ox_ullage_history_kg,   '-',  'LineWidth', lw, 'Color', [0.00 0.45 0.74]);
    plot(t_history_s, m_fuel_ullage_history_kg, '-',  'LineWidth', lw, 'Color', [0.85 0.33 0.10]);
    plot(t_history_s, m_total_n2_history,       '-',  'LineWidth', lw+0.5, 'Color', [0.47 0.67 0.19]);

    xlabel('Time [s]');
    ylabel('N_2 Gas Mass [kg]');
    title('Nitrogen Mass Distribution');
    legend('Pressurant Tank', 'LOX Ullage', 'Fuel Ullage', 'Total (Conservation Check)', 'Location', 'best');
    grid on;

    % Print mass conservation summary to command window
    mass_error_max_kg = max(m_total_n2_history) - min(m_total_n2_history);
    fprintf('\n  [PLOT CHECK] Total N2 mass variation over burn: %.2e kg (should be ~0)\n', mass_error_max_kg);
    
    % Compute N2 flow rate out of the pressurant tank
    N_steps_local = length(t_history_s) - 1;
    dt_local_s = t_history_s(2) - t_history_s(1); % Assumed constant dt
    mdot_out_kgs = zeros(1, N_steps_local + 1);
    
    % Use forward difference for the flow rate
    mdot_out_kgs(1:N_steps_local) = (m_pt_history_kg(1:N_steps_local) - m_pt_history_kg(2:end)) / dt_local_s;
    mdot_out_kgs(end) = mdot_out_kgs(end-1); % Match length to t_history_s
    
    mdot_ox_kgs = zeros(1, N_steps_local + 1);
    mdot_ox_kgs(1:N_steps_local) = (m_ox_ullage_history_kg(2:end) - m_ox_ullage_history_kg(1:N_steps_local)) / dt_local_s;
    mdot_ox_kgs(end) = mdot_ox_kgs(end-1);
    
    mdot_fuel_kgs = zeros(1, N_steps_local + 1);
    mdot_fuel_kgs(1:N_steps_local) = (m_fuel_ullage_history_kg(2:end) - m_fuel_ullage_history_kg(1:N_steps_local)) / dt_local_s;
    mdot_fuel_kgs(end) = mdot_fuel_kgs(end-1);
    
    % Standard conditions for Nitrogen (pulled from inputs)
    T_std_local_K = P.standard_temperature_k; 
    p_std_local_Pa = P.standard_pressure_pa;
    R_s_n2_jkgk = C.r_universal_jmolk / P.pressurant_molar_mass_kgmol;
    rho_std_n2_kgm3 = p_std_local_Pa / (R_s_n2_jkgk * T_std_local_K);
    
    % Convert to SCFM (1 m^3 = C.M_TO_FT^3 ft^3)
    mdot_out_scfm = (mdot_out_kgs / rho_std_n2_kgm3) * (C.M_TO_FT^3) * 60;
    mdot_ox_scfm = (mdot_ox_kgs / rho_std_n2_kgm3) * (C.M_TO_FT^3) * 60;
    mdot_fuel_scfm = (mdot_fuel_kgs / rho_std_n2_kgm3) * (C.M_TO_FT^3) * 60;
    
    % --- Subplot 5: Nitrogen Tank Pressure vs N2 Flow in SCFM ---
    if ~isempty(p_pt_history_pa)
        subplot(2,3,5);
        
        p_PSI = p_pt_history_pa * C.PA_TO_PSI; % [PSI]
        plot(mdot_out_scfm, p_PSI, '-', 'LineWidth', lw, 'Color', [0.47 0.67 0.19]); hold on;
        plot(mdot_ox_scfm, p_PSI, '-', 'LineWidth', lw, 'Color', [0.00 0.45 0.74]); 
        plot(mdot_fuel_scfm, p_PSI, '-', 'LineWidth', lw, 'Color', [0.85 0.33 0.10]);
        
        p_op_max_psi = max(P.p_op_ox_tank_pa, P.p_op_fuel_tank_pa) * C.PA_TO_PSI;
        yline(p_op_max_psi, 'r--', sprintf('%.0f PSI (Op. Limit)', p_op_max_psi), ...
            'LineWidth', lw, 'LabelHorizontalAlignment', 'left');
            
        ylabel('Pressurant Tank Pressure [PSI]');
        xlabel('N_2 Flow Rate [SCFM]');
        title('Tank Pressure vs N_2 Flow');
        legend('Total Flow', 'Flow to LOX', 'Flow to Fuel', 'Location', 'best');
        ylim([0, max(p_PSI) * 1.05]);
        grid on;
        ax = gca; ax.YAxis.Color = 'k'; ax.XAxis.Color = 'k';
    end
    
    % --- Subplot 6: N2 Flow Rate vs Time ---
    subplot(2,3,6);
    
    plot(t_history_s, mdot_out_scfm, '-', 'LineWidth', lw, 'Color', [0.47 0.67 0.19]); hold on;
    plot(t_history_s, mdot_ox_scfm, '-', 'LineWidth', lw, 'Color', [0.00 0.45 0.74]);
    plot(t_history_s, mdot_fuel_scfm, '-', 'LineWidth', lw, 'Color', [0.85 0.33 0.10]);
    
    ylabel('N_2 Flow Rate [SCFM]');
    xlabel('Time [s]');
    title('Nitrogen Flow Rate During Blowdown');
    legend('Total Flow', 'Flow to LOX', 'Flow to Fuel', 'Location', 'best');
    grid on;
    ax = gca; ax.YAxis.Color = 'k'; ax.XAxis.Color = 'k';
    
end

header_text = {
    '\bfVAPOR (Volumetric Analysis & Pressurant Output Report) — Pressurant System Thermal Analysis', ...
    sprintf('\\rmVehicle: %s | Outer Diameter: %.2f in | Burn Time: %.1f s', P.vehicle_name, P.d_tank_outer_m * C.M_TO_IN, P.t_burn_s), ...
    sprintf('Pressurant Tank: %s with volume %.2f L', tank_type, v_pressurant_tank_m3*1000)
};
sgtitle(header_text, 'FontSize', 12);

    % --- Save Figure ---
    if ~exist('Outputs', 'dir')
        mkdir('Outputs');
    end
    saveas(gcf, fullfile('Outputs', sprintf('%s_Pressurant_Thermal_Analysis.png', P.vehicle_name)));

end