function displayResults( ...
    m_ox_kg, m_fuel_kg, m_pressurant_gas_kg,                                ...
    m_empty_ox_tank_kg, m_empty_fuel_tank_kg, m_empty_pressurant_tank_kg,   ...
    m_misc_and_plumbing_kg, m_final_kg, m_total_kg,                         ...
    d_ox_tank_m, t_cyl_ox_m, l_ox_tank_total_m,                            ...
    d_fuel_tank_m, t_cyl_fuel_m, l_fuel_tank_total_m,                      ...
    d_pressurant_tank_outer_m, r_pressurant_internal_m, r_pressurant_outer_m, ...
    t_pressurant_tank_m, l_pressurant_tank_total_m,                         ...
    l_total_vehicle_m, twr_ratio, delta_v_ms, f_drag_max_n, maxq_pa, h_max_m, ...
    l_cyl_ox_m, l_cyl_fuel_m,                                                          ...
    v_ox_m3, v_fuel_m3, v_total_ox_tank_m3, v_total_fuel_tank_m3, v_pressurant_tank_m3, ...
    m_pressurant_gas_isothermal_kg, v_storage_isothermal_L,                             ...
    m_pressurant_gas_cold_kg, v_storage_cold_L,                                         ...
    m_pressurant_gas_warm_kg, v_storage_warm_L,                                         ...
    m_pressurant_gas_thermal_kg, v_storage_thermal_L,                                   ...
    P, C)
%{
---------------------------------------------------------------------------
displayResults
  Runs all design validation checks, then prints all calculated values to
  the command window in a formatted table. Any warnings generated by the
  validation checks are printed at the bottom of the output block.
  Combines what were previously validateDesign and displayResults.
  Also displays a comparison between the isothermal and thermal pressurant
  models when the thermal model is enabled.

Inputs: (all computed values from the calculation functions)
  See variable names — each maps directly to a computed result.
  m_pressurant_gas_isothermal_kg - [kg] Pressurant mass from isothermal model (old)
  v_storage_isothermal_L         - [L]  Required storage volume from isothermal model
  m_pressurant_gas_thermal_kg    - [kg] Pressurant mass from thermal model (new)
  v_storage_thermal_L            - [L]  Required storage volume from thermal model
  P  - [struct] Design inputs from getInputs()   (uses constraint limits)
  C  - [struct] Physical constants from getConstants()  (uses unit conversions)

Outputs:
  None (prints to command window only)
---------------------------------------------------------------------------
%}

%% --- VALIDATION CHECKS ---
% Checks defined in the technical plan. Warnings collected then printed at
% the end of the output block.

warning_messages = {}; % Initialize a cell array to store warning messages (There might be multiple)

% TWR Check
if twr_ratio < P.twr_minimum_ratio % Check if TWR is above the minimum requirement
    warning_messages{end+1} = sprintf('TWR is %.2f, which is below the minimum requirement of 5.', twr_ratio);
end

% Geometric Fit Check
if l_total_vehicle_m > P.l_airframe_max_m
    warning_messages{end+1} = sprintf('Estimated vehicle length (%.2f m) exceeds max airframe length (%.2f m).', l_total_vehicle_m, P.l_airframe_max_m);
end

% Cylindrical Section Length Check
if l_cyl_ox_m < 0
    warning_messages{end+1} = 'Invalid LOX tank geometry: Cylindrical section length is negative. End caps are too large for the required volume.';
end
if l_cyl_fuel_m < 0
    warning_messages{end+1} = 'Invalid Fuel tank geometry: Cylindrical section length is negative. End caps are too large for the required volume.';
end

% Input Sanity Checks (Example)
if P.ullage_fraction_fuel <= 0 || P.ullage_fraction_fuel >= 1 || P.ullage_fraction_ox <= 0 || P.ullage_fraction_ox >= 1
    warning_messages{end+1} = 'Ullage fraction must be between 0 and 1.';
end
if P.safety_factor <= 1
    warning_messages{end+1} = 'Safety factor should be greater than 1.';
end

%% --- OUTPUT DISPLAY ---

% Calculate inner diameters and total wall thicknesses for display
d_ox_tank_inner_m           = d_ox_tank_m - 2 * t_cyl_ox_m;                   % [m] LOX tank inner diameter
d_fuel_tank_inner_m         = d_fuel_tank_m - 2 * t_cyl_fuel_m;               % [m] Fuel tank inner diameter
d_pressurant_tank_inner_m   = 2 * r_pressurant_internal_m;                    % [m] Pressurant tank inner diameter
t_pressurant_total_m        = r_pressurant_outer_m - r_pressurant_internal_m; % [m] Total thickness (composite + liner)

fprintf('====================================================\n');
fprintf('      Taipan Vehicle Mass & Tank Design Results     \n');
fprintf('====================================================\n\n');

% --- Mass Breakdown ---
fprintf('--- Mass Breakdown ---\n');
fprintf('Oxidizer Mass (LOX):          %8.2f kg\n', m_ox_kg);
fprintf('Fuel Mass (Jet-A):            %8.2f kg\n', m_fuel_kg);
fprintf('Pressurant Gas Mass (N2):     %8.2f kg\n', m_pressurant_gas_kg);
fprintf('------------------------------------------\n');
fprintf('Total Propellant Mass:        %8.2f kg\n', m_ox_kg + m_fuel_kg + m_pressurant_gas_kg);
fprintf('------------------------------------------\n');
fprintf('Empty LOX Tank Mass:          %8.2f kg\n', m_empty_ox_tank_kg);
fprintf('Empty Fuel Tank Mass:         %8.2f kg\n', m_empty_fuel_tank_kg);
fprintf('Empty Pressurant Tank Mass:   %8.2f kg\n', m_empty_pressurant_tank_kg);
fprintf('Plumbing & Misc Mass:         %8.2f kg\n', m_misc_and_plumbing_kg);
fprintf('------------------------------------------\n');
fprintf('Dry Mass (Final):             %8.2f kg\n', m_final_kg);
fprintf('Wet Mass (Liftoff):           %8.2f kg\n\n', m_total_kg);

% --- Tank & Vehicle Geometry ---
fprintf('--- Tank & Vehicle Geometry ---\n\n');

% --- Volume Breakdown ---
fprintf('--- Volume Breakdown ---\n');
fprintf('LOX Volume (propellant only):    %8.4f m^3  (%8.2f L)\n', v_ox_m3,             v_ox_m3*1000);
fprintf('LOX Tank Volume (with ullage):   %8.4f m^3  (%8.2f L)\n', v_total_ox_tank_m3,  v_total_ox_tank_m3*1000);
fprintf('Fuel Volume (propellant only):   %8.4f m^3  (%8.2f L)\n', v_fuel_m3,            v_fuel_m3*1000);
fprintf('Fuel Tank Volume (with ullage):  %8.4f m^3  (%8.2f L)\n', v_total_fuel_tank_m3, v_total_fuel_tank_m3*1000);
fprintf('Pressurant Tank Volume:          %8.4f m^3  (%8.2f L)\n\n', v_pressurant_tank_m3, v_pressurant_tank_m3*1000);

fprintf('--- LOX Tank ---\n');
fprintf('Outer Diameter:  %8.4f m  (%8.2f in)  (%8.2f ft)\n', d_ox_tank_m, d_ox_tank_m*C.M_TO_IN, d_ox_tank_m*C.M_TO_FT);
fprintf('Inner Diameter:  %8.4f m  (%8.2f in)  (%8.2f ft)\n', d_ox_tank_inner_m, d_ox_tank_inner_m*C.M_TO_IN, d_ox_tank_inner_m*C.M_TO_FT);
fprintf('Wall Thickness:  %8.4f m  (%8.2f mm)  (%8.3f in)\n', t_cyl_ox_m, t_cyl_ox_m*C.M_TO_MM, t_cyl_ox_m*C.M_TO_IN);
fprintf('Total Length:    %8.4f m  (%8.2f in)  (%8.2f ft)\n', l_ox_tank_total_m, l_ox_tank_total_m*C.M_TO_IN, l_ox_tank_total_m*C.M_TO_FT);
fprintf('Total Mass:      %8.2f kg\n\n', m_empty_ox_tank_kg + m_ox_kg);

fprintf('--- Fuel Tank ---\n');
fprintf('Outer Diameter:  %8.4f m  (%8.2f in)  (%8.2f ft)\n', d_fuel_tank_m, d_fuel_tank_m*C.M_TO_IN, d_fuel_tank_m*C.M_TO_FT);
fprintf('Inner Diameter:  %8.4f m  (%8.2f in)  (%8.2f ft)\n', d_fuel_tank_inner_m, d_fuel_tank_inner_m*C.M_TO_IN, d_fuel_tank_inner_m*C.M_TO_FT);
fprintf('Wall Thickness:  %8.4f m  (%8.2f mm)  (%8.3f in)\n', t_cyl_fuel_m, t_cyl_fuel_m*C.M_TO_MM, t_cyl_fuel_m*C.M_TO_IN);
fprintf('Total Length:    %8.4f m  (%8.2f in)  (%8.2f ft)\n', l_fuel_tank_total_m, l_fuel_tank_total_m*C.M_TO_IN, l_fuel_tank_total_m*C.M_TO_FT);
fprintf('Total Mass:      %8.2f kg\n\n', m_empty_fuel_tank_kg + m_fuel_kg);

fprintf('--- Pressurant Tank (COPV) ---\n');
fprintf('Outer Diameter:  %8.4f m  (%8.2f in)  (%8.2f ft)\n', d_pressurant_tank_outer_m, d_pressurant_tank_outer_m*C.M_TO_IN, d_pressurant_tank_outer_m*C.M_TO_FT);
fprintf('Inner Diameter:  %8.4f m  (%8.2f in)  (%8.2f ft)\n', d_pressurant_tank_inner_m, d_pressurant_tank_inner_m*C.M_TO_IN, d_pressurant_tank_inner_m*C.M_TO_FT);
fprintf('Wall Thickness:  %8.4f m  (%8.2f mm)  (%8.3f in)\n', t_pressurant_total_m, t_pressurant_total_m*C.M_TO_MM, t_pressurant_total_m*C.M_TO_IN);
fprintf('Total Length:    %8.4f m  (%8.2f in)  (%8.2f ft)\n', l_pressurant_tank_total_m, l_pressurant_tank_total_m*C.M_TO_IN, l_pressurant_tank_total_m*C.M_TO_FT);
fprintf('Total Mass:      %8.2f kg\n\n', m_empty_pressurant_tank_kg + m_pressurant_gas_kg);

fprintf('--- Total Component Stackup ---\n');
fprintf('Total Length:    %8.4f m  (%8.2f in)  (%8.2f ft)\n\n', l_total_vehicle_m, l_total_vehicle_m*C.M_TO_IN, l_total_vehicle_m*C.M_TO_FT);

% --- Performance Analysis ---
fprintf('--- Performance ---\n');
fprintf('Liftoff Thrust-to-Weight Ratio (TWR): %8.2f\n', twr_ratio);
fprintf('Ideal Delta-V:                %8.2f m/s\n', delta_v_ms);
fprintf('Maximum Drag Force:           %8.2f N\n', f_drag_max_n);
fprintf('Max Q:                        %8.2f Pa\n', maxq_pa);
fprintf('Estimated Apogee:             %8.2f m    (%8.2f ft)\n\n', h_max_m, h_max_m/0.3048);

% --- Pressurant Model Comparison ---
fprintf('--- Pressurant Model Comparison ---\n');
fprintf('  Cold Bound (gas at LOX temp = %g K, absolute MAX N2):\n', P.ox_temp_k);
fprintf('    Total N2 Mass:             %8.4f kg\n', m_pressurant_gas_cold_kg);
fprintf('    Required Storage Volume:   %8.4f L\n', v_storage_cold_L);
fprintf('  Isothermal Model (Old, avg temp = %g K):\n', (P.ox_temp_k + P.pressurant_temp_k)/2);
fprintf('    Total N2 Mass:             %8.4f kg\n', m_pressurant_gas_isothermal_kg);
fprintf('    Required Storage Volume:   %8.4f L\n', v_storage_isothermal_L);
if P.use_thermal_model
    fprintf('  Transient Thermal Model (New/Active, h_ox = %g W/(m^2*K)):\n', P.h_convection_ox_wm2k);
    fprintf('    Total N2 Mass:             %8.4f kg\n', m_pressurant_gas_thermal_kg);
    fprintf('    Required Storage Volume:   %8.4f L\n', v_storage_thermal_L);
    reduction_pct = (1 - m_pressurant_gas_thermal_kg / m_pressurant_gas_isothermal_kg) * 100;
    fprintf('    Mass Reduction vs Old Isothermal: %.1f%%\n', reduction_pct);
else
    fprintf('  Transient Thermal Model: DISABLED (using isothermal values)\n');
end
fprintf('  Warm Bound (gas at inlet temp = %g K, absolute MIN N2):\n', P.pressurant_temp_k);
fprintf('    Total N2 Mass:             %8.4f kg\n', m_pressurant_gas_warm_kg);
fprintf('    Required Storage Volume:   %8.4f L\n', v_storage_warm_L);
fprintf('  ------------------------------------------\n');
if P.use_cots_tank
    fprintf('  COTS Tank (ME36) Volume:     %8.4f L\n', P.cots_tank_volume_m3 * 1000);
    active_volume_L = v_storage_thermal_L;
    if ~P.use_thermal_model
        active_volume_L = v_storage_isothermal_L;
    end
    if active_volume_L <= P.cots_tank_volume_m3 * 1000
        fprintf('  >>> ME36 tank FITS the active model requirement (%.2f L needed). <<<\n', active_volume_L);
    else
        fprintf('  >>> ME36 tank does NOT fit. Need %.2f L, have %.2f L. <<<\n', active_volume_L, P.cots_tank_volume_m3 * 1000);
    end
    fprintf('  Tank fits warm bound?   %s (need %.2f L)\n', conditional_str(v_storage_warm_L <= P.cots_tank_volume_m3 * 1000), v_storage_warm_L);
    fprintf('  Tank fits cold bound?   %s (need %.2f L)\n', conditional_str(v_storage_cold_L <= P.cots_tank_volume_m3 * 1000), v_storage_cold_L);
end
fprintf('\n');

% --- Warnings & Validation ---
if ~isempty(warning_messages)
    fprintf('!!! --- WARNINGS --- !!!\n');
    for i = 1:length(warning_messages)
        fprintf('  - %s\n', warning_messages{i});
    end
    fprintf('!!! ------------------ !!!\n');
else
    fprintf('--- All design checks passed. ---\n');
end

end

% --- Local Helper Function ---
function str = conditional_str(condition)
% Returns 'YES' or 'NO' string for a logical condition.
    if condition
        str = 'YES';
    else
        str = 'NO';
    end
end