function displayResults( ...
    m_ox_kg, m_fuel_kg, m_pressurant_gas_kg,                                ...
    m_empty_ox_tank_kg, m_empty_fuel_tank_kg, m_empty_pressurant_tank_kg,   ...
    m_misc_and_plumbing_kg, m_final_kg, m_total_kg,                         ...
    d_ox_tank_m, t_cyl_ox_m, l_ox_tank_total_m,                            ...
    d_fuel_tank_m, t_cyl_fuel_m, l_fuel_tank_total_m,                      ...
    d_pressurant_tank_outer_m, r_pressurant_internal_m, r_pressurant_outer_m, ...
    t_pressurant_tank_m, l_pressurant_tank_total_m,                         ...
    l_total_vehicle_m, twr_ratio, delta_v_ms, f_drag_max_n, maxq_pa, h_max_m, ...
    l_cyl_ox_m, l_cyl_fuel_m, P, C)
%{
---------------------------------------------------------------------------
displayResults
  Runs all design validation checks, then prints all calculated values to
  the command window in a formatted table. Any warnings generated by the
  validation checks are printed at the bottom of the output block.
  Combines what were previously validateDesign and displayResults.

Inputs: (all computed values from the calculation functions)
  See variable names — each maps directly to a computed result.
  P  - [struct] Design inputs from getInputs()   (uses constraint limits)
  C  - [struct] Physical constants from getConstants()  (uses unit conversions)

Outputs:
  None (prints to command window only)
---------------------------------------------------------------------------
%}

%% --- VALIDATION CHECKS ---
% Checks defined in the technical plan. Warnings collected then printed at
% the end of the output block.

warning_messages = {}; % Initialize a cell array to store warning messages (There might be multiple)

% TWR Check
if twr_ratio < P.twr_minimum_ratio % Check if TWR is above the minimum requirement
    warning_messages{end+1} = sprintf('TWR is %.2f, which is below the minimum requirement of 5.', twr_ratio);
end

% Geometric Fit Check
if l_total_vehicle_m > P.l_airframe_max_m
    warning_messages{end+1} = sprintf('Estimated vehicle length (%.2f m) exceeds max airframe length (%.2f m).', l_total_vehicle_m, P.l_airframe_max_m);
end

% Cylindrical Section Length Check
if l_cyl_ox_m < 0
    warning_messages{end+1} = 'Invalid LOX tank geometry: Cylindrical section length is negative. End caps are too large for the required volume.';
end
if l_cyl_fuel_m < 0
    warning_messages{end+1} = 'Invalid Fuel tank geometry: Cylindrical section length is negative. End caps are too large for the required volume.';
end

% Input Sanity Checks (Example)
if P.ullage_fraction_fuel <= 0 || P.ullage_fraction_fuel >= 1 || P.ullage_fraction_ox <= 0 || P.ullage_fraction_ox >= 1
    warning_messages{end+1} = 'Ullage fraction must be between 0 and 1.';
end
if P.safety_factor <= 1
    warning_messages{end+1} = 'Safety factor should be greater than 1.';
end

%% --- OUTPUT DISPLAY ---

% Calculate inner diameters and total wall thicknesses for display
d_ox_tank_inner_m           = d_ox_tank_m - 2 * t_cyl_ox_m;                   % [m] LOX tank inner diameter
d_fuel_tank_inner_m         = d_fuel_tank_m - 2 * t_cyl_fuel_m;               % [m] Fuel tank inner diameter
d_pressurant_tank_inner_m   = 2 * r_pressurant_internal_m;                    % [m] Pressurant tank inner diameter
t_pressurant_total_m        = r_pressurant_outer_m - r_pressurant_internal_m; % [m] Total thickness (composite + liner)

fprintf('====================================================\n');
fprintf('      Taipan Vehicle Mass & Tank Design Results     \n');
fprintf('====================================================\n\n');

% --- Mass Breakdown ---
fprintf('--- Mass Breakdown ---\n');
fprintf('Oxidizer Mass (LOX):          %8.2f kg\n', m_ox_kg);
fprintf('Fuel Mass (Jet-A):            %8.2f kg\n', m_fuel_kg);
fprintf('Pressurant Gas Mass (N2):     %8.2f kg\n', m_pressurant_gas_kg);
fprintf('------------------------------------------\n');
fprintf('Total Propellant Mass:        %8.2f kg\n', m_ox_kg + m_fuel_kg + m_pressurant_gas_kg);
fprintf('------------------------------------------\n');
fprintf('Empty LOX Tank Mass:          %8.2f kg\n', m_empty_ox_tank_kg);
fprintf('Empty Fuel Tank Mass:         %8.2f kg\n', m_empty_fuel_tank_kg);
fprintf('Empty Pressurant Tank Mass:   %8.2f kg\n', m_empty_pressurant_tank_kg);
fprintf('Plumbing & Misc Mass:         %8.2f kg\n', m_misc_and_plumbing_kg);
fprintf('------------------------------------------\n');
fprintf('Dry Mass (Final):             %8.2f kg\n', m_final_kg);
fprintf('Wet Mass (Liftoff):           %8.2f kg\n\n', m_total_kg);

% --- Tank & Vehicle Geometry ---
fprintf('--- Tank & Vehicle Geometry ---\n\n');

fprintf('--- LOX Tank ---\n');
fprintf('Outer Diameter:  %8.4f m  (%8.2f in)  (%8.2f ft)\n', d_ox_tank_m, d_ox_tank_m*C.M_TO_IN, d_ox_tank_m*C.M_TO_FT);
fprintf('Inner Diameter:  %8.4f m  (%8.2f in)  (%8.2f ft)\n', d_ox_tank_inner_m, d_ox_tank_inner_m*C.M_TO_IN, d_ox_tank_inner_m*C.M_TO_FT);
fprintf('Wall Thickness:  %8.4f m  (%8.2f mm)  (%8.3f in)\n', t_cyl_ox_m, t_cyl_ox_m*C.M_TO_MM, t_cyl_ox_m*C.M_TO_IN);
fprintf('Total Length:    %8.4f m  (%8.2f in)  (%8.2f ft)\n', l_ox_tank_total_m, l_ox_tank_total_m*C.M_TO_IN, l_ox_tank_total_m*C.M_TO_FT);
fprintf('Total Mass:      %8.2f kg\n\n', m_empty_ox_tank_kg + m_ox_kg);

fprintf('--- Fuel Tank ---\n');
fprintf('Outer Diameter:  %8.4f m  (%8.2f in)  (%8.2f ft)\n', d_fuel_tank_m, d_fuel_tank_m*C.M_TO_IN, d_fuel_tank_m*C.M_TO_FT);
fprintf('Inner Diameter:  %8.4f m  (%8.2f in)  (%8.2f ft)\n', d_fuel_tank_inner_m, d_fuel_tank_inner_m*C.M_TO_IN, d_fuel_tank_inner_m*C.M_TO_FT);
fprintf('Wall Thickness:  %8.4f m  (%8.2f mm)  (%8.3f in)\n', t_cyl_fuel_m, t_cyl_fuel_m*C.M_TO_MM, t_cyl_fuel_m*C.M_TO_IN);
fprintf('Total Length:    %8.4f m  (%8.2f in)  (%8.2f ft)\n', l_fuel_tank_total_m, l_fuel_tank_total_m*C.M_TO_IN, l_fuel_tank_total_m*C.M_TO_FT);
fprintf('Total Mass:      %8.2f kg\n\n', m_empty_fuel_tank_kg + m_fuel_kg);

fprintf('--- Pressurant Tank (COPV) ---\n');
fprintf('Outer Diameter:  %8.4f m  (%8.2f in)  (%8.2f ft)\n', d_pressurant_tank_outer_m, d_pressurant_tank_outer_m*C.M_TO_IN, d_pressurant_tank_outer_m*C.M_TO_FT);
fprintf('Inner Diameter:  %8.4f m  (%8.2f in)  (%8.2f ft)\n', d_pressurant_tank_inner_m, d_pressurant_tank_inner_m*C.M_TO_IN, d_pressurant_tank_inner_m*C.M_TO_FT);
fprintf('Wall Thickness:  %8.4f m  (%8.2f mm)  (%8.3f in)\n', t_pressurant_total_m, t_pressurant_total_m*C.M_TO_MM, t_pressurant_total_m*C.M_TO_IN);
fprintf('Total Length:    %8.4f m  (%8.2f in)  (%8.2f ft)\n', l_pressurant_tank_total_m, l_pressurant_tank_total_m*C.M_TO_IN, l_pressurant_tank_total_m*C.M_TO_FT);
fprintf('Total Mass:      %8.2f kg\n\n', m_empty_pressurant_tank_kg + m_pressurant_gas_kg);

fprintf('--- Total Component Stackup ---\n');
fprintf('Total Length:    %8.4f m  (%8.2f in)  (%8.2f ft)\n\n', l_total_vehicle_m, l_total_vehicle_m*C.M_TO_IN, l_total_vehicle_m*C.M_TO_FT);

% --- Performance Analysis ---
fprintf('--- Performance ---\n');
fprintf('Liftoff Thrust-to-Weight Ratio (TWR): %8.2f\n', twr_ratio);
fprintf('Ideal Delta-V:                %8.2f m/s\n', delta_v_ms);
fprintf('Maximum Drag Force:           %8.2f N\n', f_drag_max_n);
fprintf('Max Q:                        %8.2f Pa\n', maxq_pa);
fprintf('Estimated Apogee:             %8.2f m    (%8.2f ft)\n\n', h_max_m, h_max_m/0.3048);

% --- Warnings & Validation ---
if ~isempty(warning_messages)
    fprintf('!!! --- WARNINGS --- !!!\n');
    for i = 1:length(warning_messages)
        fprintf('  - %s\n', warning_messages{i});
    end
    fprintf('!!! ------------------ !!!\n');
else
    fprintf('--- All design checks passed. ---\n');
end

end
